apiVersion: v2
name: keycloak-spa
description: A Helm chart for Keycloak SPA application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - keycloak
  - spa
  - authentication
  - oidc
home: https://github.com/your-org/keycloak-spa
sources:
  - https://github.com/your-org/keycloak-spa
maintainers:
  - name: Your Name
    email: your.email@example.com
