apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak-spa.fullname" . }}-secret
  labels:
    {{- include "keycloak-spa.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  oidc-issuer: {{ .Values.secrets.oidc.issuer | b64enc | quote }}
  oidc-authorize-url: {{ .Values.secrets.oidc.authorizeUrl | b64enc | quote }}
  oidc-token-url: {{ .Values.secrets.oidc.tokenUrl | b64enc | quote }}
  oidc-userinfo-url: {{ .Values.secrets.oidc.userinfoUrl | b64enc | quote }}
  oidc-client-id: {{ .Values.secrets.oidc.clientId | b64enc | quote }}
  oidc-client-secret: {{ .Values.secrets.oidc.clientSecret | b64enc | quote }}
  oidc-callback-url: {{ .Values.secrets.oidc.callbackUrl | b64enc | quote }}
